version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: joyeria_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@joyeria.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build: .
    container_name: joyeria_web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://root:3bwYw8hKY0Bw8KmOfYM5TCSUkZG3y10q@dpg-cvlg9195pdvs73a4goe0-a.oregon-postgres.render.com:5432/joyass"
      FLASK_ENV: production
    volumes:
      - .:/app

volumes:
  pgadmin_data: